export const data = [
    
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',
         'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quod accusantium consectetur harum incidunt fugiat, eos beatae similique quae, a quam dolores nemo veniam. Unde facere iure delectus blanditiis in inventore recusandae, sed architecto, error doloribus nisi voluptates repellat nemo quisquam, labore earum! Adipisci exercitationem officiis ipsum quasi officia. Eius, nihil?',


]